<?php
// $Id$
/**
 * @file
 * Broadcast Dashboard module file
 * 
 * This module "broadcasts" pre-written or custom inserted text to specified areas of a website when switched on.
 */

/**
 * Implements hook_help().
 */
function broadcast_dashboard_help($path, $arg) {
  if ($path === 'admin/help#broadcast-dashboard') {
    return t ('The Broadcast Dashboard module allows for text notifications to be pushed to specified areas of the website when switched on.');
  }
}

/**
 * Implements hook_menu().
 */
function broadcast_dashboard_menu() {
  $items = array();

  $items['admin/config/system/broadcast_dashboard'] = array(
    'title' => 'Broadcast Dashboard',
    'description' => 'Configuration for the Broadcast Dashboard module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('broadcast_dashboard_form'),
    'access arguments' => 'adminster content',
    'type' => MENU_NORMAL_ITEM,
  );
}

/**
 * Implements hook_form().
 */
function broadcast_dashboard_form() {
  $form['broadcast_dashboard_custom_message'] = array (
    '#type' => 'textfield',
    '#default_value' => variable_get('broadcast_dashboard_custom_message',
                                     'Broadcast Dashboard Custom Message'),
    '#title' => t('Broadcast Dashboard Custom Message'),
    '#description' => t('Custom message to appear in place of pre-written notification text.'),
    '#size' => 60,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
return $form;
}

/**
 * Implements hook_form_submit()
 */
function broadcast_dashboard_form_submit($form, &$form_state) {
  
}